service: nest-standalone-serverless

frameworkVersion: ^2.40.0

provider:
  name: aws
  lambdaHashingVersion: 20201221
  runtime: nodejs14.x

plugins:
  - serverless-offline
  - serverless-pseudo-parameters

functions:
  testEnpoint:
    handler: dist/src/lambdas/lambda-kinesis-entry-point.handler
    events:
      - http:
          path: consumeKinesis
          method: get